blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using gostruct
    url: https://github.com/projectdiscovery/gostruct/discussions/categories/q-a
    about: Ask a question or request support for using gostruct

  - name: Share idea / feature to discuss for gostruct
    url: https://github.com/projectdiscovery/gostruct/discussions/categories/ideas
    about: Share idea / feature to discuss for gostruct

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication